framework:
    secret: '%env(APP_SECRET)%'
    session:
        cookie_lifetime: 15
        gc_maxlifetime: 15


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
